# Generated by Django 2.1 on 2018-11-27 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181127_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 5, 24, 24, 199341, tzinfo=utc)),
        ),
    ]
